In [1]:
import numpy as np 

In [9]:
def quat2rot(q):
    R = np.array([[q[0]**2 + q[1]**2 - q[2]**2 - q[3]**2, - 2*(q[1] * q[2] - q[0] * q[3]),    -      2*(q[1] * q[3] + q[0] * q[2])],
                  [- 2*(q[1] * q[2] + q[0] * q[3]),         q[0]**2 - q[1]**2 + q[2]**2 - q[3]**2, 2*(q[2] * q[3] - q[0] * q[1])],
                  [- 2*(q[1] * q[3] - q[0] * q[2]),         2*(q[2] * q[3] + q[0] * q[1]),         q[0]**2 - q[1]**2 - q[2]**2 + q[3]**2]])
    return R
                  

def quat2zyz(q):
    r23 =  (q[2] * q[3] - q[1] * q[0])
    r13 =  (q[1] * q[3] + q[2] * q[0])
    r33 =  1 - 2*(q[1]**2 + q[2] ** 2)
    r31 =  (q[1] * q[3] - q[2] * q[0])
    r32 =  (q[2] * q[3] + q[1] * q[0])
    if r33 != 0:
        y = np.arccos(r33)
        x = np.arctan2(r32, r31)
        z = np.arctan2(r23, -r13)
        
    return np.array([x,y,z])

def quaternion_to_euler(q):
    (w, x, y, z) = (q[0], q[1], q[2], q[3])
    t0 = +2.0 * (w * x + y * z)
    t1 = +1.0 - 2.0 * (x * x + y * y)
    roll = np.arctan2(t0, t1)
    t2 = +2.0 * (w * y - z * x)
    t2 = +1.0 if t2 > +1.0 else t2
    t2 = -1.0 if t2 < -1.0 else t2
    pitch = np.arcsin(t2)
    t3 = +2.0 * (w * z + x * y)
    t4 = +1.0 - 2.0 * (y * y + z * z)
    yaw = np.arctan2(t3, t4)
    return np.array([roll, pitch, yaw])

def quatmult(x,y):
    return np.array([x[0]*y[0] - x[1]*y[1] - x[2]*y[2] - x[3]*y[3],
                     x[0]*y[1] + x[1]*y[0] + x[2]*y[3] - x[3]*y[2],
                     x[0]*y[2] - x[1]*y[3] + x[2]*y[0] + x[3]*y[1],
                     x[0]*y[3] + x[1]*y[2] - x[2]*y[1] + x[3]*y[0]])

def euler_to_quaternion(r):
    (yaw, pitch, roll) = (r[0], r[1], r[2])
    qz = np.sin(roll/2) * np.cos(pitch/2) * np.cos(yaw/2) - np.cos(roll/2) * np.sin(pitch/2) * np.sin(yaw/2)
    qy = np.cos(roll/2) * np.sin(pitch/2) * np.cos(yaw/2) + np.sin(roll/2) * np.cos(pitch/2) * np.sin(yaw/2)
    qx = np.cos(roll/2) * np.cos(pitch/2) * np.sin(yaw/2) - np.sin(roll/2) * np.sin(pitch/2) * np.cos(yaw/2)
    qw = np.cos(roll/2) * np.cos(pitch/2) * np.cos(yaw/2) + np.sin(roll/2) * np.sin(pitch/2) * np.sin(yaw/2)
    return np.array([qw, qx, qy, qz])

In [10]:
def r_x(x): 
    return np.array([[1,0,0], [0, np.cos(x), - np.sin(x)], [0, np. sin(x), np.cos(x)]])
def r_y(x): 
    return np.array( [[np.cos(x), 0, np.sin(x)], [0,1,0], [-np. sin(x), 0 ,  np.cos(x)]])
def r_z(x): 
    return np.array([[np.cos(x), - np.sin(x), 0], [np. sin(x), np.cos(x),0], [0,0,1]])


def xyz2quat(x,y,z):
    qx = np.array([np.cos(x/2), np.sin(x/2), 0, 0])
    qy = np.array([np.cos(y/2), 0, np.sin(y/2), 0])
    qz = np.array([np.cos(z/2), 0, 0, np.sin(z/2)])
    return quatmult(qx, quatmult(qy, qz))

def zyz2quat(x,y,z):
    qx = np.array([np.cos(x/2), 0, 0, np.sin(x/2)])
    qy = np.array([np.cos(y/2), 0, np.sin(y/2), 0])
    qz = np.array([np.cos(z/2), 0, 0, np.sin(z/2)])
    return quatmult(qx, quatmult(qy, qz))

def zyz2xyz(x,y,z):
    R = r_z(x) @ r_y(y) @ r_z(z)
    x = np.arctan(- R[1,2]/R[2,2])
    y = np.arcsin(R[0,2])
    z = np.arctan(-R[0,1] /R[0,0])
    return x,y,z

def xyz2zyz(e):
    R = r_x(e[0]) @ r_y(e[1]) @ r_z(e[2])
    if R[2,2] != 0:
        y = np.arccos(R[2,2])
        z = -np.arctan2(R[2,1], R[2,0]) +np.pi
        x = np.arctan2(R[1,2], R[0,2])
        
    return np.array([x,y,z])

In [11]:
# transforms points to quaterniions and back
x = 0.0
y = 0.3 
z = 1.3
xyz2quat(*zyz2xyz(x,y,z)) #- euler_to_quaternion(zyz2xyz(x,y,z))

array([0.78714464, 0.09043793, 0.11896528, 0.59839081])

In [104]:
MRP_H2R(np.array([1,0,0,0]))

NameError: name 'MRP_H2R' is not defined

In [8]:
#define transformation from H to R³
## works

def MRP_H2R(q):
    return 4 * q[1:]/(1+q[0])

def MRP_R2H(e):
    return 1/(16 + np.linalg.norm(e)**2) * np.array([16 - np.linalg.norm(e)**2, *8*e])

In [12]:
# complex conjugated 
def quat_cc(q):
    d = np.copy(q)
    d[1:] *= -1
    return d

In [13]:
x = 0
y = 0.5 
z = 1
a = euler_to_quaternion(zyz2xyz(x,y,z))

In [ ]:
quat2rot(a).T

In [17]:
from numpy import sin, cos
def r_z_r_y_r_z(ret, v):
    ret[0,0] = -sin(v[0])*sin(v[2]) + cos(v[0])*cos(v[1])*cos(v[2])
    ret[0,1] = sin(v[0])*cos(v[2]) + sin(v[2])*cos(v[0])*cos(v[1])
    ret[0,2] = - sin(v[1])*cos(v[0])
    ret[1,0] = - sin(v[0])*cos(v[1])*cos(v[2]) - sin(v[2])*cos(v[0])
    ret[1,1] = -sin(v[0])*sin(v[2])*cos(v[1]) + cos(v[0])*cos(v[2])
    ret[1,2] = sin(v[0])*sin(v[1])
    ret[2,0] = sin(v[1])*cos(v[2])
    ret[2,1] = sin(v[1])*sin(v[2])
    ret[2,2] = cos(v[1])
    

In [ ]:
R = np.zeros((3,3))
r_z_r_y_r_z(R, [0,0.5,1])

In [ ]:
R

In [22]:
R = np.zeros((3,3))
r_z_r_y_r_z(R, [0,0.5,1])

In [23]:
R

array([[ 0.47415988,  0.73846026, -0.47942554],
       [-0.84147098,  0.54030231,  0.        ],
       [ 0.25903472,  0.40342268,  0.87758256]])

In [364]:
MRP_H2R(np.array([1,0,0,0]))

array([0., 0., 0.])

In [365]:
import sympy as s
def r_x(x): 
    return np.array([[1,0,0], [0, s.cos(x), - s.sin(x)], [0, s.sin(x), s.cos(x)]])
def r_y(x): 
    return np.array( [[s.cos(x), 0, s.sin(x)], [0,1,0], [-s.sin(x), 0 ,  s.cos(x)]])
def r_z(x): 
    return np.array([[s.cos(x), - s.sin(x), 0], [s.sin(x), s.cos(x),0], [0,0,1]])



In [367]:
x = s.Symbol('zyz[0]')
y = s.Symbol('zyz[1]')
z = s.Symbol('zyz[2]')
r_z(x) @ r_y(y) @ r_z(z)

array([[-sin(zyz[0])*sin(zyz[2]) + cos(zyz[0])*cos(zyz[1])*cos(zyz[2]),
        -sin(zyz[0])*cos(zyz[2]) - sin(zyz[2])*cos(zyz[0])*cos(zyz[1]),
        sin(zyz[1])*cos(zyz[0])],
       [sin(zyz[0])*cos(zyz[1])*cos(zyz[2]) + sin(zyz[2])*cos(zyz[0]),
        -sin(zyz[0])*sin(zyz[2])*cos(zyz[1]) + cos(zyz[0])*cos(zyz[2]),
        sin(zyz[0])*sin(zyz[1])],
       [-sin(zyz[1])*cos(zyz[2]), sin(zyz[1])*sin(zyz[2]), cos(zyz[1])]],
      dtype=object)

In [1]:
import bonndit.utilc.quaternions as qu
import matplotlib.pyplot as plt
import numpy as np

In [2]:
a = np.zeros((4))
a = np.random.random(size=4)
ret = np.zeros((3))
qu.MPR_H2R_q(ret, a,a)

In [13]:
x = np.array((0,0.5,0.5))
qu.ZYZ2quat(a,x)

In [4]:
b = np.random.normal(0,0.05,(3, 20))

In [5]:
c = np.zeros((4,20))
d = np.zeros((3,3,20))
e = np.zeros((3,3))
for i in range(20):
    qu.MPR_R2H_q(c[:,i], b[:,i], a)

In [6]:
for i in range(20):
    qu.quat2rot(d[:,:,i], c[:,i])

In [7]:
d[...,0] 

array([[ 0.70515573, -0.52605702,  0.47541498],
       [ 0.46097591,  0.84958221,  0.25634211],
       [-0.53875468,  0.03839374,  0.84158738]])

In [14]:
quat2rot(xyz2quat(*zyz2xyz(*x)))

array([[ 0.77015115,  0.42073549, -0.47942554],
       [-0.47942554,  0.87758256,  0.        ],
       [ 0.42073549,  0.22984885,  0.87758256]])

In [15]:
qu.quat2rot(e, a)

In [18]:
h =np.zeros((3,3))
r_z_r_y_r_z(h, x)

In [22]:
h

array([[ 0.77015115,  0.42073549, -0.47942554],
       [-0.47942554,  0.87758256,  0.        ],
       [ 0.42073549,  0.22984885,  0.87758256]])

In [23]:
e

array([[ 0.77015115, -0.47942554,  0.42073549],
       [ 0.42073549,  0.87758256,  0.22984885],
       [-0.47942554,  0.        ,  0.87758256]])

In [24]:
quat2rot(a)

array([[ 0.77015115,  0.42073549, -0.47942554],
       [-0.47942554,  0.87758256,  0.        ],
       [ 0.42073549,  0.22984885,  0.87758256]])

In [28]:
%matplotlib qt
from matplotlib import cm
fig = plt.figure()
ax = fig.add_subplot(projection='3d')
ax.scatter3D(c[0], c[1], c[2], alpha=0.1)

In [124]:
pip install .


Processing /home/johannes/UniBonn/forschung/bonndit
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
  Created wheel for bonndit: filename=bonndit-0.2.0-cp38-cp38-linux_x86_64.whl size=30475114 sha256=86b185840995448654db99d0d555096e5e7b05294ba496e686717c7db5abe377
  Stored in directory: /tmp/pip-ephem-wheel-cache-qpjmt06x/wheels/2e/1e/92/44625976e847c3f0ac3a02bc8b14a2722cbba93db73d0e6491
Successfully built bonndit
  Attempting uninstall: numpy
    Found existing installation: numpy 1.20.0
    Uninstalling numpy-1.20.0:
      Successfully uninstalled numpy-1.20.0
  Attempting uninstall: bonndit
    Found existing installation: bonndit 0.2.0
    Uninstalling bonndit-0.2.0:
      Successfully uninstalled bonndit-0.2.0

[notice] A new release of pip is available: 23.0.

In [128]:
pip uninstall numpy -y

Found existing installation: numpy 1.24.3
Uninstalling numpy-1.24.3:
  Successfully uninstalled numpy-1.24.3
Note: you may need to restart the kernel to use updated packages.


In [129]:
pip install numpy==1.20.0

  Using cached numpy-1.20.0-cp38-cp38-manylinux2010_x86_64.whl (15.4 MB)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyshtools 4.10.1 requires numpy>=1.23.2, but you have numpy 1.20.0 which is incompatible.

[notice] A new release of pip is available: 23.0.1 -> 23.1.1
[notice] To update, run: /home/johannes/UniBonn/forschung/bonndit/venv/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
