# Compare response functions

In [1]:
import numpy as np
from os.path import expanduser
import os

In [2]:
home = expanduser("~")
DATA_DIR = os.path.join(home, 'Devel/test/samuel/in4michi')
NEW_MICHI = os.path.join(DATA_DIR, '../michi_results')
OLD_MICHI = os.path.join(DATA_DIR, '../response_out')
BONNDIT = os.path.join(DATA_DIR, 'results/')

In [3]:
new = np.load(os.path.join(NEW_MICHI, 'response.npz'))
old = np.load(os.path.join(OLD_MICHI, 'response.npz'))
bonndit = np.load(os.path.join(BONNDIT, 'response.npz'))

In [4]:
print(new.keys())
print(old.keys())
print(bonndit.keys())

['gm', 'wm', 'radial_order', 'angular_order', 'csf', 'zeta', 'tau']
['zeta', 'tau', 'gm', 'csf', 'wm']
['csf', 'zeta', 'tau', 'bvals', 'order', 'bvecs', 'wm', 'gm']


In [6]:
for key in new.keys():
    try:
        print(key, (bonndit[key] - old[key]) / old[key])
    except KeyError:
        pass

gm [ 2.90468288e-07  4.17851716e-07 -5.36032696e-07 -5.26160471e-02
 -5.58813968e-03 -4.55134162e-02]
wm [ 8.14411638e-08 -1.87731929e-07 -5.61221318e-07 -2.77409124e-03
 -2.71863685e-03 -8.63210422e-03]
csf [ 1.39234510e-07 -5.76172554e-07 -2.85478759e-07  2.70387103e-02
 -5.93701403e-02 -1.12234821e-01]
zeta 0.0
tau 0.0


## bonndit: response

In [13]:
from subprocess import check_output
from os.path import expanduser
import os

home = expanduser("~")
DATA_DIR = os.path.join(home, 'Devel/test/samuel/in4michi/test_data_3d')
OUT_DIR = os.path.join(DATA_DIR, 'results')

SCRIPT = 'mtdeconv '
venv = '. ' + os.path.join(home, 'Devel/venvs/bonndit/bin/activate') + ' && '

command = venv + SCRIPT + '{dire}/ -o {out}/bonndit/response.npz -R'.format(dire=DATA_DIR, out = OUT_DIR)
print(command)
out = check_output(command, shell = True)

for line in out.splitlines():
    print(line.decode("utf-8") )

. /home/olivier/Devel/venvs/bonndit/bin/activate && mtdeconv /home/olivier/Devel/test/samuel/in4michi/test_data_3d/ -o /home/olivier/Devel/test/samuel/in4michi/test_data_3d/results/bonndit/response.npz -R
[ 91630.14341921 -90293.49816839 198821.42034613  -1862.08321471
  -3533.46985724   1819.94948964  -6950.72853925   1594.54974228
   7658.01907531  10714.8513791   -4648.0012886   14927.16297285
  -7096.84849699   3378.03902714   1627.07112555  -1001.82836474
  -2332.79240924   -374.92361589   1401.79979683   1685.72044752
    405.32203625   1465.4953763 ]
[ 8.70920736e+04 -6.57037346e+03  9.91882517e+03  2.49892301e+03
 -8.24038099e+02  6.13779173e+02  9.82964705e+02  3.84092796e+02
  3.68710544e+02  1.03128125e+03 -5.97560442e+02  1.02164337e+02
  9.93072979e+02 -4.77292769e+01 -2.40448954e+01  3.80460506e+02
  1.38669246e+02  1.34105873e+03 -2.81963948e+02 -1.20198890e+03
 -5.27712811e+02 -6.77988373e+01]


## Old code michi: response

In [1]:
from subprocess import check_output
from os.path import expanduser
import os

home = expanduser("~")
DATA_DIR = os.path.join(home, 'Devel/test/samuel/in4michi/test_data_3d')
OUT_DIR = os.path.join(DATA_DIR, 'results')

SCRIPT = 'python2 /home/olivier/Devel/mic-tools/scripts/msmt-deconv/shore-response.py '
venv = '. ' + os.path.join(home, 'Devel/venvs/bonndit/bin/activate') + ' && '

command = venv + SCRIPT + '{dire}/ {out}/old_michi/'.format(dire=DATA_DIR, out = OUT_DIR)
print(command)
out = check_output(command, shell = True)

for line in out.splitlines():
    print(line.decode("utf-8") )

. /home/olivier/Devel/venvs/bonndit/bin/activate && python2 /home/olivier/Devel/mic-tools/scripts/msmt-deconv/shore-response.py /home/olivier/Devel/test/samuel/in4michi/test_data_3d/ /home/olivier/Devel/test/samuel/in4michi/test_data_3d/results/old_michi/
4 4
/home/olivier/Devel/test/samuel/in4michi/test_data_3d/dti_FA.nii.gz
Using provided DTI mask.
loading data....
reshaping...
csf response:
('  0.0%',)
    done   
3 voxel
[  9.16301660e+04  -9.02934493e+04   1.98821362e+05  -2.23875288e+03
   3.44210202e+03   1.16744800e+03  -6.97973007e+03  -1.78303965e+03
   8.46359966e+03  -1.03158867e+04  -3.25269229e+03   1.48611223e+04
   7.66528862e+03   3.40274544e+03  -1.90877332e+03  -7.99447267e+02
   2.13461183e+03  -1.22077248e+02   1.54785180e+03  -1.76300482e+03
   2.37200709e+02  -1.33040030e+03]
[  91630.16601105  -90293.44934797  198821.36167508]
grey matter response:
('  0.0%',)
    done   
5 voxel
[  8.70920574e+04  -6.57033379e+03   9.91880255e+03   2.54672819e+03
   8.02103552e

In [18]:
bonndit = '91630.14341921 -90293.49816839 198821.42034613  -1862.08321471 -3533.46985724   1819.94948964  -6950.72853925 \
1594.54974228 7658.01907531  10714.8513791   -4648.0012886   14927.16297285 \
-7096.84849699   3378.03902714   1627.07112555  -1001.82836474 \
-2332.79240924   -374.92361589   1401.79979683   1685.72044752 \
405.32203625   1465.4953763'.replace('  ', ' ').replace('  ', ' ').split(' ')

old = '9.16301660e+04  -9.02934493e+04   1.98821362e+05  -2.23875288e+03 \
3.44210202e+03   1.16744800e+03  -6.97973007e+03  -1.78303965e+03 \
8.46359966e+03  -1.03158867e+04  -3.25269229e+03   1.48611223e+04 \
7.66528862e+03   3.40274544e+03  -1.90877332e+03  -7.99447267e+02 \
2.13461183e+03  -1.22077248e+02   1.54785180e+03  -1.76300482e+03 \
2.37200709e+02  -1.33040030e+03'.replace('  ', ' ').replace('  ', ' ').split(' ')

import numpy as np
np.array([float(x) for x in bonndit]) - [float(x) for x in old]

array([-2.25807900e-02, -4.88683900e-02,  5.83461300e-02,  3.76669665e+02,
       -6.97557188e+03,  6.52501490e+02,  2.90015307e+01,  3.37758939e+03,
       -8.05580585e+02,  2.10307381e+04, -1.39530900e+03,  6.60406728e+01,
       -1.47621371e+04, -2.47064129e+01,  3.53584445e+03, -2.02381098e+02,
       -4.46740424e+03, -2.52846368e+02, -1.46052003e+02,  3.44872527e+03,
        1.68121327e+02,  2.79589568e+03])

In [19]:
np.array([-2.25807900e-02, -4.88683900e-02,  5.83461300e-02,  3.76669665e+02,
       -6.97557188e+03,  6.52501490e+02,  2.90015307e+01,  3.37758939e+03,
       -8.05580585e+02,  2.10307381e+04, -1.39530900e+03,  6.60406728e+01,
       -1.47621371e+04, -2.47064129e+01,  3.53584445e+03, -2.02381098e+02,
       -4.46740424e+03, -2.52846368e+02, -1.46052003e+02,  3.44872527e+03,
        1.68121327e+02,  2.79589568e+03]) == np.array([-2.25807900e-02, -4.88683900e-02,  5.83461300e-02,  3.76669665e+02,
       -6.97557188e+03,  6.52501490e+02,  2.90015307e+01,  3.37758939e+03,
       -8.05580585e+02,  2.10307381e+04, -1.39530900e+03,  6.60406728e+01,
       -1.47621371e+04, -2.47064129e+01,  3.53584445e+03, -2.02381098e+02,
       -4.46740424e+03, -2.52846368e+02, -1.46052003e+02,  3.44872527e+03,
        1.68121327e+02,  2.79589568e+03])



array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

## Compare shore matrix

In [44]:
import importlib.util
spec = importlib.util.spec_from_file_location("shore_old", "/home/olivier/Devel/mic-tools/packages/dwmri/shore.py")
old_shore = importlib.util.module_from_spec(spec)
spec.loader.exec_module(old_shore)

In [47]:
from bonndit.michi import shore as new_shore

In [49]:
order = 4
zeta = 700


import os
from dipy.io import read_bvals_bvecs
from dipy.core.gradients import gradient_table


DATA_DIR = "/home/olivier/Devel/test/samuel/in4michi/"

bvals, bvecs = read_bvals_bvecs(os.path.join(DATA_DIR,"bvals"), os.path.join(DATA_DIR,"bvecs"))
gtab = gradient_table(bvals, bvecs)


In [50]:
new_matrix = new_shore.matrix(order, order, zeta, gtab, tau=1 / (4 * np.pi ** 2))
old_matrix = old_shore.matrix(order, order, zeta, gtab, tau=1 / (4 * np.pi ** 2))

/home/olivier/Devel/venvs/bonndit/lib/python3.5/site-packages/dipy/core/geometry.py:129: RuntimeWarning: invalid value encountered in true_divide
  theta = np.arccos(z / r)


In [52]:
(new_matrix-old_matrix)/old_matrix

/home/olivier/Devel/venvs/bonndit/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[ 0.00000000e+00, -1.13713118e-16,  0.00000000e+00, ...,
                    nan,             nan,             nan],
       [ 0.00000000e+00, -1.13713118e-16,  0.00000000e+00, ...,
                    nan,             nan,             nan],
       [ 0.00000000e+00, -1.13713118e-16,  0.00000000e+00, ...,
                    nan,             nan,             nan],
       ...,
       [ 0.00000000e+00, -1.31110442e-16, -0.00000000e+00, ...,
         1.81749783e-15, -2.59013033e-16, -3.43387926e-16],
       [ 0.00000000e+00,  1.31110334e-16,  1.67706836e-16, ...,
        -4.86620665e-16,  4.15549331e-16, -1.45889119e-16],
       [ 0.00000000e+00, -0.00000000e+00, -0.00000000e+00, ...,
         1.35780765e-16, -2.87266694e-16,  0.00000000e+00]])

In [27]:
from bonndit.michi import shore
np.zeros((97,97,49) + (shore.get_size(4, 4),)).shape

(97, 97, 49, 22)