# Compare response functions

In [1]:
import numpy as np
from os.path import expanduser
import os

In [2]:
home = expanduser("~")
DATA_DIR = os.path.join(home, 'Devel/test/samuel/in4michi')
NEW_MICHI = os.path.join(DATA_DIR, '../michi_results')
OLD_MICHI = os.path.join(DATA_DIR, '../response_out')
BONNDIT = os.path.join(DATA_DIR, 'results/')

In [3]:
new = np.load(os.path.join(NEW_MICHI, 'response.npz'))
old = np.load(os.path.join(OLD_MICHI, 'response.npz'))
bonndit = np.load(os.path.join(BONNDIT, 'response.npz'))

In [4]:
print(new.keys())
print(old.keys())
print(bonndit.keys())

['gm', 'wm', 'radial_order', 'angular_order', 'csf', 'zeta', 'tau']
['zeta', 'tau', 'gm', 'csf', 'wm']
['csf', 'zeta', 'tau', 'bvals', 'order', 'bvecs', 'wm', 'gm']


In [6]:
for key in new.keys():
    try:
        print(key, (bonndit[key] - old[key]) / old[key])
    except KeyError:
        pass

gm [ 2.90468288e-07  4.17851716e-07 -5.36032696e-07 -5.26160471e-02
 -5.58813968e-03 -4.55134162e-02]
wm [ 8.14411638e-08 -1.87731929e-07 -5.61221318e-07 -2.77409124e-03
 -2.71863685e-03 -8.63210422e-03]
csf [ 1.39234510e-07 -5.76172554e-07 -2.85478759e-07  2.70387103e-02
 -5.93701403e-02 -1.12234821e-01]
zeta 0.0
tau 0.0


## bonndit: response

In [24]:
from subprocess import check_output
from os.path import expanduser
import os

home = expanduser("~")
DATA_DIR = os.path.join(home, 'Devel/test/samuel/in4michi/test_data_3d')
OUT_DIR = os.path.join(DATA_DIR, 'results')

SCRIPT = 'mtdeconv.py '
venv = '. ' + os.path.join(home, 'Devel/venvs/bonndit/bin/activate') + ' && '

command = venv + SCRIPT + '{dire}/ -o {out}/bonndit/response.npz -R'.format(dire=DATA_DIR, out = OUT_DIR)
print(command)
out = check_output(command, shell = True)

for line in out.splitlines():
    print(line.decode("utf-8") )

. /home/olivier/Devel/venvs/bonndit/bin/activate && mtdeconv.py /home/olivier/Devel/test/samuel/in4michi/test_data_3d/ -o /home/olivier/Devel/test/samuel/in4michi/test_data_3d/results/bonndit/response.npz -R
[[[0 0 1]
  [0 0 0]
  [0 0 0]]

 [[0 0 1]
  [0 0 0]
  [0 0 0]]

 [[0 0 1]
  [0 0 0]
  [0 0 0]]]


## Old code michi: response

In [31]:
SCRIPT = 'python2 /home/olivier/Devel/mic-tools/scripts/msmt-deconv/shore-response.py '
venv = '. ' + os.path.join(home, 'Devel/venvs/bonndit/bin/activate') + ' && '

command = venv + SCRIPT + '{dire}/ {out}/old_michi/'.format(dire=DATA_DIR, out = OUT_DIR)
print(command)
out = check_output(command, shell = True)

for line in out.splitlines():
    print(line.decode("utf-8") )

. /home/olivier/Devel/venvs/bonndit/bin/activate && python2 /home/olivier/Devel/mic-tools/scripts/msmt-deconv/shore-response.py /home/olivier/Devel/test/samuel/in4michi/test_data_3d/ /home/olivier/Devel/test/samuel/in4michi/test_data_3d/results/old_michi/
4 4
/home/olivier/Devel/test/samuel/in4michi/test_data_3d/dti_FA.nii.gz
Using provided DTI mask.
[[[0 0 1]
  [0 0 0]
  [0 0 0]]

 [[0 0 1]
  [0 0 0]
  [0 0 0]]

 [[0 0 1]
  [0 0 0]
  [0 0 0]]]
loading data....
reshaping...
csf response:
  0.0    done   
3 voxel
[  91630.16601105  -90293.44934797  198821.36167508]
grey matter response:
  0.0    done   
5 voxel
[ 87092.05740841  -6570.33378911   9918.80255351]
white matter response:
  0.0% 0 voxel
    done   
[ 0.  0.  0.  0.  0.  0.]
